/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedCircularProgressBar: typeof import('./src/components/ui/animated-circular-progressbar/AnimatedCircularProgressBar.vue')['default']
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
    BlackHoleBackground: typeof import('./src/components/ui/bg-black-hole/BlackHoleBackground.vue')['default']
    ChatArea: typeof import('./src/components/ai/ChatArea.vue')['default']
    'ChatArea.test': typeof import('./src/components/ai/ChatArea.test.vue')['default']
    ChatInput: typeof import('./src/components/ai/ChatInput.vue')['default']
    EncryptedText: typeof import('./src/components/ui/encrypted-text/EncryptedText.vue')['default']
    FallingStarsBg: typeof import('./src/components/ui/bg-falling-stars/FallingStarsBg.vue')['default']
    FileUpload: typeof import('./src/components/ui/file-upload/FileUpload.vue')['default']
    FileUploadGrid: typeof import('./src/components/ui/file-upload/FileUploadGrid.vue')['default']
    FlipCard: typeof import('./src/components/ui/flip-card/FlipCard.vue')['default']
    FluidCursor: typeof import('./src/components/ui/fluid-cursor/FluidCursor.vue')['default']
    IconCloud: typeof import('./src/components/ui/icon-cloud/IconCloud.vue')['default']
    InteractiveHoverButton: typeof import('./src/components/ui/interactive-hover-button/InteractiveHoverButton.vue')['default']
    KnowledgeSelector: typeof import('./src/components/ai/KnowledgeSelector.vue')['default']
    MessageItem: typeof import('./src/components/ai/MessageItem.vue')['default']
    'MessageItem.test': typeof import('./src/components/ai/MessageItem.test.vue')['default']
    MessageList: typeof import('./src/components/ai/MessageList.vue')['default']
    ModelSelector: typeof import('./src/components/ai/ModelSelector.vue')['default']
    MorphingTabs: typeof import('./src/components/ui/morphing-tabs/MorphingTabs.vue')['default']
    MorphingText: typeof import('./src/components/ui/morphing-text/MorphingText.vue')['default']
    PromptSelector: typeof import('./src/components/ai/PromptSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollIsland: typeof import('./src/components/ui/scroll-island/ScrollIsland.vue')['default']
    SessionItem: typeof import('./src/components/ai/SessionItem.vue')['default']
    'SessionItem.test': typeof import('./src/components/ai/SessionItem.test.vue')['default']
    SessionList: typeof import('./src/components/ai/SessionList.vue')['default']
    'SessionList.test': typeof import('./src/components/ai/SessionList.test.vue')['default']
    SessionSidebar: typeof import('./src/components/ai/SessionSidebar.vue')['default']
    ShimmerButton: typeof import('./src/components/ui/shimmer-button/ShimmerButton.vue')['default']
    SleekLineCursor: typeof import('./src/components/ui/sleek-line-cursor/SleekLineCursor.vue')['default']
    SparklesText: typeof import('./src/components/ui/sparkles-text/SparklesText.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    ToolCallStatus: typeof import('./src/components/ai/ToolCallStatus.vue')['default']
  }
}
