/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedCircularProgressBar: typeof import('./src/components/ui/animated-circular-progressbar/AnimatedCircularProgressBar.vue')['default']
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
    BlackHoleBackground: typeof import('./src/components/ui/bg-black-hole/BlackHoleBackground.vue')['default']
    EncryptedText: typeof import('./src/components/ui/encrypted-text/EncryptedText.vue')['default']
    FallingStarsBg: typeof import('./src/components/ui/bg-falling-stars/FallingStarsBg.vue')['default']
    FileUpload: typeof import('./src/components/ui/file-upload/FileUpload.vue')['default']
    FileUploadGrid: typeof import('./src/components/ui/file-upload/FileUploadGrid.vue')['default']
    FlipCard: typeof import('./src/components/ui/flip-card/FlipCard.vue')['default']
    FluidCursor: typeof import('./src/components/ui/fluid-cursor/FluidCursor.vue')['default']
    IconCloud: typeof import('./src/components/ui/icon-cloud/IconCloud.vue')['default']
    InteractiveHoverButton: typeof import('./src/components/ui/interactive-hover-button/InteractiveHoverButton.vue')['default']
    MorphingTabs: typeof import('./src/components/ui/morphing-tabs/MorphingTabs.vue')['default']
    MorphingText: typeof import('./src/components/ui/morphing-text/MorphingText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollIsland: typeof import('./src/components/ui/scroll-island/ScrollIsland.vue')['default']
    ShimmerButton: typeof import('./src/components/ui/shimmer-button/ShimmerButton.vue')['default']
    SleekLineCursor: typeof import('./src/components/ui/sleek-line-cursor/SleekLineCursor.vue')['default']
    SparklesText: typeof import('./src/components/ui/sparkles-text/SparklesText.vue')['default']
  }
}
